package com.openclassrooms.magicgithub.api

import android.os.Build
import androidx.annotation.RequiresApi
import com.openclassrooms.magicgithub.model.User

class FakeApiService : ApiService {
    private val _users = FakeApiServiceGenerator.FAKE_USERS.toMutableList()

    /**
     * Return a list of [User]
     * Those users must be generated by [FakeApiServiceGenerator]
     */
    override fun getUsers(): List<User> {
        return _users.toList() // Retourne une copie pour éviter les modifications extérieures
    }

    /**
     * Generate a random [User] and add it to the [FakeApiService.users] list.
     * This user must be retrieved from the [FakeApiServiceGenerator.FAKE_USERS_RANDOM] list.
     */
    override fun addRandomUser() {
        val randomUser = FakeApiServiceGenerator.FAKE_USERS_RANDOM.random()

        // ✅ Correction : S'assurer que la liste reste toujours à 20 éléments
        if (_users.size >= 20) {
            _users.removeAt(0) // Supprime le plus ancien utilisateur pour maintenir la taille
        }

        _users.add(randomUser)
    }

    /**
     * Delete a [User] from the [FakeApiService.users] list.
     */
    @RequiresApi(Build.VERSION_CODES.N)
    override fun deleteUser(user: User) {
        _users.removeIf { it.id == user.id }
    }
}
